version: '3.5'


services:
  
  mariadb:
    build: mariadb
    image: mariadb
    container_name: maria_debe
    networks:
      - da_net
    volumes:
      - "mariadb_v:/var/lib/mysql"
    restart: always
    env_file:
      - .env

  nginx:
    build: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    image: nginx
    container_name: nginx_c
    networks:
      - da_net
    volumes:
      - "wordpress_v:/var/www"
    restart: always
    env_file:
      - .env


  wordpress:
    build: wordpress
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress_c
    networks:
      - da_net
    volumes:
      - "wordpress_v:/var/www"
    restart: always
    env_file:
      - .env

networks:
  da_net:
    external: false
    name: da_net

volumes:
  wordpress_v:
    driver: local                                                            
    driver_opts:                                                             
      type: none                                                           
      o: bind          
      device: /home/abiju-du/data/files
  mariadb_v:
    driver: local                                                            
    driver_opts:                                                             
      type: none                                                           
      o: bind          
      device: /home/abiju-du/data/dump
