version: '3.5'

services:
  nginx:
    build: nginx
    ports:
      - "8080:80"
    container_name: nginx_c
    networks:
      - da_net
    volumes:
      - "wordpress_v:/var/www"
  
  mariadb:
    build: mariadb
    container_name: maria_debe
    networks:
      - da_net

  wordpress:
    build: wordpress
    container_name: wordpress_c
    networks:
      - da_net
    volumes:
      - "wordpress_v:/var/www"

networks:
  da_net:
    external: false
    name: da_net

volumes:
  wordpress_v: