version: '3.5'


services:
  
  mariadb:
    build: mariadb
    container_name: maria_debe
    networks:
      - da_net
    # volumes:
    #   - "./mariadb/script.sql:/docker-entrypoint-initdb.d/wp.sql"
    # environment:
    #   - MYSQL_ROOT_PASSWORD=chut
    #   - MYSQL_DATABASE=mysql
    #   - MYSQL_USER=mysql
    #   - MYSQL_PASSWORD=chut
  nginx:
    build: nginx
    depends_on:
      - wordpress
    ports:
      - "8080:80"
    container_name: nginx_c
    networks:
      - da_net
    volumes:
      - "wordpress_v:/var/www"

  wordpress:
    build: wordpress
    depends_on:
      - mariadb
    container_name: wordpress_c
    networks:
      - da_net
    volumes:
      - "wordpress_v:/var/www"

networks:
  da_net:
    external: false
    name: da_net

volumes:
  wordpress_v:
    driver: local                                                            
    driver_opts:                                                             
      type: none                                                           
      o: bind          
      device: /goinfre/abiju-du/docker/volumes/inception_wordpress_v/_data # <-- create this directory in host
