version: '3.5'


services:
  
  mariadb:
    build: mariadb
    container_name: maria_debe
    networks:
      - da_net
    volumes:
      - "mariadb_v:/var/lib/mysql"
    # volumes:
    #   - "./mariadb/script.sql:/docker-entrypoint-initdb.d/wp.sql"
    # environment:
    #   - MYSQL_ROOT_PASSWORD=chut
    #   - MYSQL_DATABASE=mysql
    #   - MYSQL_USER=mysql
    #   - MYSQL_PASSWORD=chut
  nginx:
    build: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    container_name: nginx_c
    networks:
      - da_net
    volumes:
      - "wordpress_v:/var/www"

  wordpress:
    build: wordpress
    depends_on:
      - mariadb
    container_name: wordpress_c
    networks:
      - da_net
    volumes:
      - "wordpress_v:/var/www"

networks:
  da_net:
    external: false
    name: da_net

volumes:
  wordpress_v:
    driver: local                                                            
    driver_opts:                                                             
      type: none                                                           
      o: bind          
      device: /home/abiju-du/data/files # <-- create this directory in host and modify hosts file
  mariadb_v:
    driver: local                                                            
    driver_opts:                                                             
      type: none                                                           
      o: bind          
      device: /home/abiju-du/data/dump # <-- create this directory in host and modify hosts file
